from ._novosparc import setup_for_OT_reconstruction, find_spatial_archetypes, get_genes_from_spatial_archetype, find_spatially_related_genes
from ._GWadjusted import tensor_square_loss_adjusted, gromov_wasserstein_adjusted_norm
